/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileMovement */

#ifndef _Included_FileMovement
#define _Included_FileMovement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileMovement
 * Method:    fileMove
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_FileMovement_fileMove
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
