/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileCopy */

#ifndef _Included_FileCopy
#define _Included_FileCopy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileCopy
 * Method:    copyFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_FileCopy_copyFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
